FROM jupyter/minimal-notebook
EXPOSE 8888
CMD ["jupyter", "lab", "--ip='0.0.0.0'", "--port=8888", "--no-browser", "--allow-root"]
USER root
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git curl wget openjdk-8-jdk
RUN export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ADD notebooks4docker /home/jovyan
RUN pip install git+https://github.com/JMendes1995/py_heideltime
USER root
RUN wget https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/russian.par.gz
RUN wget https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/estonian.par.gz
RUN gunzip russian.par.gz
RUN gunzip estonian.par.gz
RUN cp russian.par /opt/conda/lib/python3.7/site-packages/py_heideltime/Heideltime/TreeTaggerLinux/lib/russian.par
RUN cp estonian.par /opt/conda/lib/python3.7/site-packages/py_heideltime/Heideltime/TreeTaggerLinux/lib/estonian.par
RUN rm russian.par
RUN rm estonian.par
RUN chmod 111 /opt/conda/lib/python3.7/site-packages/py_heideltime/Heideltime/TreeTaggerLinux/bin/*
USER jovyan